format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$all\
$nodejs\
$cmd_duration $jobs $time\
$line_break\
$character"""

[os]
disabled = true
[os.symbols]
Macos = "🥭  " 

[nodejs]
format = 'via [🤖 $version](bold green) '

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " 🔒"
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = "+ "
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
symbol = "🐏 "

[rust]
symbol = "🦀 "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[aws]
format = 'on [$symbol$region]($style) '
style = 'bold blue'
symbol = '🅰 '
[aws.region_aliases]
ap-southeast-2 = 'au'
us-east-1 = 'va'

[docker_context]
format = 'via [🐋 $context](blue bold)'

[gcloud]
symbol = '🌩️ '
format = '[$symbol$project]($style) '
style = 'bold yellow'

[golang]
format = '[🏎💨 $version](bold cyan) '

[helm]
format = '[⎈ $version](bold white) '

[kubernetes]
format = 'on [⚙️ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'gke_.*_(?P<var_cluster>[\\w-]+)' = 'gke-$var_cluster'
[kubernetes.user_aliases]
'dev.local.cluster.k8s' = 'dev'
'root/.*' = 'root'

[lua]
format = '[🌕 $version](bold blue) '

[python]
format = '[${symbol}(\($virtualenv\))]($style) '
pyenv_version_name = true

[shell]
fish_indicator = ''
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
zsh_indicator = ''
style = 'cyan bold'
disabled = false

[sudo]
style = 'bold green'
symbol = '👨🏽 💻 '
disabled = false

[terraform]
format = '[$symbol $workspace]($style) '

[username]
style_user = 'green bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true
